# Generated by Django 4.1.5 on 2024-02-07 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapde', '0012_product_stock_alter_order_date_alter_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 7, 20, 32, 6, 408959)),
        ),
    ]
