# Generated by Django 4.1.5 on 2024-02-19 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapde', '0016_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 2, 19, 16, 23, 21, 366822, tzinfo=datetime.timezone.utc)),
        ),
    ]
